server:
  port: 8080
spring:
  main:
    banner-mode: off
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none

  sql:
    init:
      schema-locations: classpath:db/changelog/init-db.sql
      data-locations: classpath:db/changelog/data.sql
      mode: always




