server:
  port: 8080
spring:
  main:
    banner-mode: off
  datasource:
    url: jdbc:mysql://localhost:3306/online_school
    username: root
    password: Liubasa1993.
  jpa:
    hibernate:
      ddl-auto: none

  sql:
    init:
      schema-locations: classpath:db/changelog/init-db.sql
      data-locations: classpath:db/changelog/data.sql
      mode: always




