server:
  port: 8088
spring:
  main:
    banner-mode: off
  datasource:
    url: jdbc:mysql://localhost:3306/online_school
#  ${DATASOURCE_URL}
    username: root
#  ${DATASOURCE_USERNAME}
    password: Liubasa1993.
#  ${DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none

  sql:
    init:
      schema-locations: classpath:db/changelog/init-db.sql
      data-locations: classpath:db/changelog/data.sql
      mode: always
#
#logging:
#  level:
#    root: debug



