server:
  port: 8889

spring:
  main:
    banner-mode: off
  messages:
    basename: ValidationMessages

  datasource:
    url: jdbc:mysql://${DATASOURCE_DATABASE_HOST}:${DATASOURCE_DATABASE_PORT}/${DATASOURCE_DATABASE_NAME}?allowMultiQueries=true
    username: ${DATASOURCE_DATABASE_USERNAME}
    password: ${DATASOURCE_DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml

logging:
    level:
      root: info